---
title: "Reproducible documents"
author: "Alicia Muñoz Espinosa"
format: html
editor: visual
---

```{r setup}
library(tidyverse)
```

## "About me"

- Alicia

- UAEIS

**Researcher** with focus in *Public Health*

## "Simple code"

```{r}
3 * 3
```

```{r}
2 + 2
```

```{r}
#| message: false
#| warning: false
library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

## Showing the data

```{r}
post_meal_data
```

```{r}
glimpse(post_meal_data)
```

```{r}
ggplot(post_meal_data, aes(x = BMI))
```

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

 

```{r}
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

## Excercise: discrete plots

```{r}
#| fig-cap: "Personas con medición de glicemia"
#| label: fig-conteo-glicemia
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

## Plotting two discrete variables

```{r}
ggplot(post_meal_data, aes(x = Group, fill = glykemi)) +
  geom_bar()
```

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
